version: "3"
services:
  flask_app:
    build:
      context: ./
      dockerfile: ./flask_app/Dockerfile.flask
    ports:
      - 5000:5000
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq
      - CELERY_RESULT_BACKEND=redis://redis
      - OPENAI_API_KEY=KEY_HERE # OpenAI API key for Flask app
    depends_on:
      - rabbitmq
      - redis
  reactjs_frontend:
    build:
      context: ./
      dockerfile: ./reactjs_frontend/Dockerfile.reactjs
    ports:
      - 5173:5173
  celery_worker:
    build:
      context: ./
      dockerfile: ./celery_worker/Dockerfile.celery
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq
      - CELERY_RESULT_BACKEND=redis://redis
      - OPENAI_API_KEY=KEY_HERE # OpenAI API key for Celery worker
    depends_on:
      - rabbitmq
      - redis

  rabbitmq:
    image: "rabbitmq:management-alpine"
    ports:
      - "15672:15672"

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

networks:
  default:
    name: cel_net
