version: "3"
services:
  fastapi_server:
    build:
      context: ./
      dockerfile: ./fastapi_server/Dockerfile.fastapi
    ports:
      - 5000:5000
    environment:
      - OPENAI_API_KEY=KEY_HERE # OpenAI API key for Flask app
  reactjs_frontend:
    build:
      context: ./
      dockerfile: ./reactjs_frontend/Dockerfile.reactjs
    ports:
      - 5173:5173

networks:
  default:
    name: cel_net
